# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 赵毛毛博客
subtitle: 赵毛毛博客的个人网站
description: 赵毛毛博客，赵毛毛博客的个人网站
author: 赵毛毛博客
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://woca.so
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
   github: git@github.com:SxxYu/SxxYu.github.io.git 
   #gitcafe: git@gitcafe.com:daoyi/daoyi.git
   #coding: git@git.coding.net:luodaoyi/blog.git

#社交连接
social:
  GitHub: https://github.com/luodaoyi
  微博: http://weibo.com/5727891308/profile?topnav=1&wvr=6
  #知乎: http://www.zhihu.com/people/daguanren
  #Twitter: https://twitter.com/luodaoyi

#多说评论
duoshuo_shortname: luodaoyi

#百度统计
baidu_analytics: 227548a37676c557885bb56cd147b82f

#rss
feed:
  type: atom
  path: atom.xml
  limit: 0

#博客年份
since: 2015

#许可方式
creative_commons: by-nc-sa

#头像路径
avatar: http://s.luodaoyi.com/blog.jpg

#友情链接
links_title: Links
links:
  大官人服务器: https://52res.taobao.com
  畅爽游戏加速器: http://www.52res.com
  七牛云存储: https://portal.qiniu.com/signup?code=3lid1lwcyi9g2

#多说热门文章
duoshuo_hotartical: true

#多说分享
#duoshuo_share: true

#首页文章预览
index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
